# Generated by Django 4.2 on 2026-02-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_remove_produto_codigo_barras_and_more'),
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='finalizada',
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
