# Generated by Django 4.2 on 2026-03-04 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdv', '0002_remove_itemvenda_subtotal_remove_venda_finalizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberto', models.BooleanField(default=True)),
                ('abertura_em', models.DateTimeField(auto_now_add=True)),
                ('fechamento_em', models.DateTimeField(blank=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
